### ISSUE TITLE
SondeHub as a telemetry source

### ISSUE THREAD

**Issue by maciejopalinski** [projecthorus/chasemapper#56]
Is it possible to use multiple flight data sources?
For example:
1. SondeHub stations (when you are far away and not getting any signal yourself)
2. Other source, RDZ TTGO (when you are close and you receive more packets than stations on SondeHub)

Is there any other software that can provide me with this functionality?

**Comment by darksidelemm** [comment]
I had considered adding a sondehub 'importer'.... but I haven't done it. 

Chasemapper was written to be a (mostly) offline tracking system. I didn't really want to link it into online services more than was necessary (e.g. tawhiri for balloon predictions).

It's probably possible to do, but not high on my priority list (and any work on chasemapper is pretty low on my priority list at the moment!)

**Comment by maciejopalinski** [comment]
I am considering implementing this feature, but I would need to know if it follows this project assumptions. If it does, I would love to contribute and create a pull request. If it's not something you would like in this project, I will probably create a fork. Let me know

**Comment by darksidelemm** [comment]
I'm not sure its going to be quite that simple unfortunately. Sourcing data from somewhere like Sondehub is going to be quite a bit different from how chasemapper works right now, since you will *have* to filter to a particular radiosonde serial, otherwise the amount of traffic coming in to chasemapper is going to be huge (e.g. every radiosonde around the world...).

So that means more UI elements to select a serial number, etc... quite a lot of changes. You'd also have to deal with the many duplicate telemetry packets (and out-of-order packets!) that arrive via sondehub, things that chasemapper doesn't deal with because it never needed to.

Honestly, I'm not sure these changes are worth it. If you're going to be relying on internet access, look at Sondehub.org at the start of the chase, then switch to chasemapper once you have signal.

If you want to pull in data from sondehub, then I'd suggest that it be a separate program which does the websockets connection, filtering, etc, and emits data as UDP in the payload summary format.

**Comment by maciejopalinski** [comment]
I understand, thank you.
